version: "3"

services:
  db:
    image: postgres:14.5-alpine
    container_name: patrachar_postgres
    restart: always
    volumes:
      - ./_postgres_data:/var/lib/postgresql/data/
      - ./files:/var/lib/postgresql/
    env_file:
      - env.txt
    networks:
      - v-network
  redis:
    image: redis:alpine
    restart: always
    container_name: patrachar_redis
    command: redis-server --appendonly yes
    volumes:
      - ./_redis_data:/var/lib/redis
      - ./redis/rc.local:/etc/rc.local
    networks:
      - v-network
  web:
    image: project/patrachar:0.0.2
    restart: always
    container_name: patrachar_web
    ports:
      - 8800:8000
    volumes:
      - ./sock/:/sock/
      - ./project/:/usr/src/app/
      - ./logs/:/logs/
      - ./static/:/static/
    command: sh entrypoint.sh
    env_file:
      - env.txt
    networks:
      - v-network
    environment:
      - PYTHONUNBUFFERED=1
      - DEPLOY_LEVEL=${DEPLOY}

  worker:
    image: project/patrachar:0.0.2
    restart: always
    container_name: worker
    command: "celery -A project worker -l INFO"
    env_file:
      - env.txt
    volumes:
      - ./project/:/usr/src/app/
    networks:
      - v-network

  consumer:
    image: project/patrachar:0.0.2
    restart: always
    container_name: patrachar_consumer
    volumes:
      - ./sock/:/sock/
      - ./project/:/usr/src/app/
      - ./logs/:/logs/
      - ./static/:/static/
    command: python consumer.py
    env_file:
      - env.txt
    networks:
      - v-network
    depends_on:
      - web
    environment:
      - PYTHONUNBUFFERED=1

  nginx:
    image: nginx:latest
    container_name: patrachar_nginx
    restart: always
    ports:
      - 8811:80
      - 444:443
    volumes:
      - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
      - ./react/dist:/var/www/frontend
      - ./static/:/var/www/static
      - ./project/media/:/var/www/media
      - ./sock/:/sock/
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - web
      # - worker
    networks:
      - v-network

networks:
  v-network:
    external: false
