# Generated by Django 3.2.25 on 2024-09-25 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=255, null=True)),
                ('answer', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.PositiveIntegerField(blank=True, null=True)),
                ('date', models.CharField(blank=True, max_length=10)),
                ('paper_count', models.CharField(max_length=10)),
                ('draft', models.BooleanField(default=True)),
                ('sender', models.CharField(blank=True, max_length=255, null=True)),
                ('sender_phone', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('receiving_department', models.CharField(blank=True, max_length=255, null=True)),
                ('receiving_department_id', models.PositiveIntegerField(blank=True, null=True)),
                ('settlement_branch', models.CharField(blank=True, max_length=255, null=True)),
                ('settlement_branch_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('attachment', models.JSONField(default=list)),
                ('chalani_number', models.CharField(blank=True, max_length=255, null=True)),
                ('received_date', models.CharField(blank=True, max_length=10)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by_fullname', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by_organization', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='PaperDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='untitled', max_length=255)),
                ('file', models.FileField(upload_to='')),
                ('no_pages', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SerialNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.PositiveIntegerField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.department')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serialnumbers', to='templates.paper')),
            ],
        ),
    ]
