# Generated by Django 3.2.25 on 2024-10-02 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_department_is_dartachalani'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('templates', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.PositiveIntegerField()),
                ('active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.department')),
            ],
        ),
        migrations.RenameField(
            model_name='paper',
            old_name='received_date',
            new_name='paper_date',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='receiving_department_id',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='settlement_branch',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='settlement_branch_id',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='verified',
        ),
        migrations.RemoveField(
            model_name='paperdocument',
            name='no_pages',
        ),
        migrations.RemoveField(
            model_name='paperdocument',
            name='title',
        ),
        migrations.AddField(
            model_name='paper',
            name='first_reponder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reponses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paper',
            name='page_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paperdocument',
            name='chalani_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='paperdocument',
            name='receiving_branch',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paperdocument',
            name='receiving_department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paperdocument',
            name='sending_branch',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paperdocument',
            name='sending_department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paperdocument',
            name='subject',
            field=models.CharField(default='untitled', max_length=255),
        ),
        migrations.AlterField(
            model_name='paper',
            name='receiving_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.department'),
        ),
        migrations.AlterField(
            model_name='paperdocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='SerialNumber',
        ),
        migrations.AddField(
            model_name='relatedbranch',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serialnumbers', to='templates.paper'),
        ),
    ]
