# Generated by Django 3.2.25 on 2024-10-07 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_department_is_dartachalani'),
        ('templates', '0003_auto_20241002_1121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relatedbranch',
            old_name='organization',
            new_name='department',
        ),
        migrations.AddField(
            model_name='relatedbranch',
            name='fiscal_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='branches.fiscalyear'),
            preserve_default=False,
        ),
    ]
