# Generated by Django 3.2.25 on 2024-10-07 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0004_auto_20241007_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='receiving_department',
        ),
    ]
