# Generated by Django 3.2.25 on 2024-10-07 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0005_remove_paper_receiving_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperdocument',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='templates.paper'),
        ),
    ]
