# Generated by Django 3.2.25 on 2024-10-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0006_alter_paperdocument_paper'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatedbranch',
            name='remarks',
            field=models.CharField(default='N/A', max_length=255),
        ),
    ]
