# Generated by Django 3.2.25 on 2024-09-25 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_en', models.CharField(blank=True, max_length=255, null=True)),
                ('district_np', models.CharField(blank=True, max_length=255, null=True)),
                ('name_np', models.CharField(blank=True, max_length=255, null=True)),
                ('name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('fullname_np', models.CharField(blank=True, max_length=255, null=True)),
                ('fullname_en', models.CharField(blank=True, max_length=255, null=True)),
                ('address_np', models.CharField(blank=True, max_length=255, null=True)),
                ('address_en', models.CharField(blank=True, max_length=255, null=True)),
                ('province_np', models.CharField(blank=True, max_length=255, null=True)),
                ('province_en', models.CharField(blank=True, max_length=255, null=True)),
                ('slogan_np', models.CharField(blank=True, max_length=255, null=True)),
                ('slogan_en', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_np', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_en', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('main_logo', models.CharField(blank=True, max_length=2083, null=True)),
                ('campaign_logo', models.CharField(blank=True, max_length=2083, null=True)),
                ('users', models.JSONField(default=dict)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ('name_en', 'name_np'),
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('enabled', models.BooleanField(default=False)),
                ('description', models.CharField(default='', max_length=255)),
                ('entity', models.CharField(choices=[('BE', 'BE'), ('FE', 'FE'), ('FB', 'FB')], default='BE', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_np', models.CharField(blank=True, max_length=255, null=True)),
                ('name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('alias', models.CharField(blank=True, max_length=255, null=True)),
                ('address_np', models.CharField(blank=True, max_length=255, null=True)),
                ('address_en', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('phone_np', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_en', models.CharField(blank=True, max_length=255, null=True)),
                ('slogan_np', models.CharField(blank=True, max_length=255, null=True)),
                ('slogan_en', models.CharField(blank=True, max_length=255, null=True)),
                ('main_logo', models.CharField(blank=True, max_length=2083, null=True)),
                ('campaign_logo', models.CharField(blank=True, max_length=2083, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='branches.branch')),
            ],
        ),
    ]
