# Generated by Django 3.2.25 on 2024-10-02 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='is_dartachalani',
            field=models.BooleanField(default=False),
        ),
    ]
