# Generated by Django 3.2.25 on 2024-09-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('operator', 'operator'), ('superuser', 'superuser')], default='operator', max_length=25),
        ),
    ]
